---
- name: user creation
  user:
    name: "{{ user }}"
    comment: "{{ user }}"
    home: /opt/{{ user }}

- name: folder creation
  file:
    path: /opt/{{ item }}
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0755
  with_items:
    - "{{ user }}/logs"
    - "{{ user }}/release"
    - "{{ user }}/bin"
    - jdk

- name: Extract JDK11 to jdk directory
  unarchive:
    src: https://bkash-devops-tools.s3-ap-southeast-1.amazonaws.com/amazon-corretto-11.0.7.10.1-linux-x64.tar.gz
    dest: /opt/jdk
    extra_opts: [ --strip-components=1 ]
    remote_src: yes

- name: JDK profile
  copy:
    src: jdk11.sh
    dest: /etc/profile.d/

- name: Source JDK profile file
  shell: source /etc/profile.d/jdk11.sh

- name: java alternatives path installation
  command: alternatives --install /usr/bin/java java /opt/jdk/bin/java 2

- name: copy stop, check & restart bash script file to bin folder
  template:
    src: "{{ item }}.j2"
    dest: /opt/{{ user }}/bin/{{ item }}
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0755
  with_items:
    - stop.sh
    - restart.sh
    - start.sh

- name: copy java11 system service
  template:
    src: java11.service.j2
    dest: /usr/lib/systemd/system/java11.service

- name: java11 service enable
  systemd:
    name: java11
    enabled: yes
    masked: no

- name: artifact deployment
  copy:
    src: "{{ artifacts_directory }}/{{ module_name }}.jar"    # check the jar_file_name, directory
    dest: /opt/{{ user }}/release/{{ module_name }}.jar
    owner: "{{ user }}"
    group: "{{ user }}"
  notify: Restart Java11

- name: Force a restart if configuration has changed
  meta: flush_handlers

- name: sleep timeout
  shell: sleep 10s
